# Use Nginx Alpine as the base image
FROM nginx:1.21.3-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Copy the build output from your React application to the container
COPY build/ ./

# Copy the Nginx configuration file from the project root to the container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]# Use Nginx Alpine as the base image
FROM nginx:1.21.3-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Copy the build output from your React application to the container
COPY build/ ./

# Copy the Nginx configuration file from the project root to the container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]